### ISSUE TITLE
travis login from command line

### ISSUE THREAD

**Issue by piyushp3** [forcedotcom/sfdx-travisci#136]
trying to login from gitbash or  windows cmd . keep  seeing  the login error
Last Exception
An error occurred running `travis login`:
    RuntimeError: Unknown error
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:212:in `rescue in basic_auth'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:216:in `login'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:81:in `possible_tokens'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:50:in `each_token'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:37:in `with_token'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli/login.rb:31:in `login'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli/login.rb:40:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli/command.rb:198:in `execute'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli.rb:64:in `run'
        from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/bin/travis:18:in `<top (required)>'
        from C:/Ruby26-x64/bin/travis:23:in `load'
        from C:/Ruby26-x64/bin/travis:23:in `<main>'

**Comment by piyushp3** [comment]
> Last Exception
> An error occurred running travis login:
> RuntimeError: Unknown error
> from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:212:in rescue in basic_auth' from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:208:in basic_auth'
> from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:216:in login' from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:81:in possible_tokens'
> from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:50:in each_token' from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/tools/github.rb:37:in with_token'
> from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli/login.rb:31:in login' from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli/login.rb:40:in run'
> from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli/command.rb:198:in execute' from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/lib/travis/cli.rb:64:in run'
> from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/travis-1.8.13/bin/travis:18:in <top (required)>' from C:/Ruby26-x64/bin/travis:23:in load'
> from C:/Ruby26-x64/bin/travis:23:in `'
any idea why  I cannot seem to login using gitbash or windows cmd .keep seeing this  error

**Comment by ajfmo** [comment]
I'm running this same issue:

```
Username: ajfmo
Password for ajfmo: *********
Not Found
for a full error report, run travis report

ajfm@DESKTOP-FJTHL36 MINGW64 ~/Desktop/ideaProjects/ICRM-DevOrg (main)
$ travis report
System
Ruby:                     Ruby 3.0.0-p0
Operating System:         Windows
RubyGems:                 RubyGems 3.2.3

CLI
Version:                  1.10.0
Plugins:                  none
Auto-Completion:          yes
Last Version Check:       2021-02-04 14:00:04 -0500

Session
API Endpoint:             https://api.travis-ci.org/
Logged In:                no
Verify SSL:               yes
Enterprise:               no

Endpoints
org:                      https://api.travis-ci.org/ (current)
com:                      https://api.travis-ci.com/ ()

Last Exception
An error occurred running `travis login`:
    RuntimeError: Not Found
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/tools/github.rb:212:in `rescue in basic_auth'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/tools/github.rb:208:in `basic_auth'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/tools/github.rb:216:in `login'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/tools/github.rb:81:in `possible_tokens'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/tools/github.rb:50:in `each_token'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/tools/github.rb:37:in `with_token'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/cli/login.rb:31:in `login'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/cli/login.rb:50:in `run'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/cli/command.rb:200:in `execute'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/lib/travis/cli.rb:64:in `run'
        from C:/tools/ruby30/lib/ruby/gems/3.0.0/gems/travis-1.10.0/bin/travis:18:in `<top (required)>'
        from C:/tools/ruby30/bin/travis:23:in `load'
        from C:/tools/ruby30/bin/travis:23:in `<main>'

For issues with the command line tool, please visit https://github.com/travis-ci/travis.rb/issues.
For Travis CI in general, go to https://github.com/travis-ci/travis-ci/issues or email support@travis-ci.com.
```
